# Generated by Django 4.2.9 on 2024-01-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="content",
            field=models.TextField(max_length=140),
        ),
    ]
